# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 519)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #1D2B64, stop:1#F8CDDA);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #9796f0, stop:1 #9796f0);\n"
"\n"
"border-radius:15px;")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 40, 431, 451))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #1D2B64, stop:1 #1D2B64);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #9796f0, stop:1 #fbc7d4);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelicon = QtWidgets.QLabel(self.frame)
        self.labelicon.setGeometry(QtCore.QRect(80, 10, 301, 231))
        self.labelicon.setText("")
        self.labelicon.setPixmap(QtGui.QPixmap("../65dca69f78972935caf61580e7c17bd9.png"))
        self.labelicon.setObjectName("labelicon")
        self.lineEditusername = QtWidgets.QLineEdit(self.frame)
        self.lineEditusername.setGeometry(QtCore.QRect(100, 270, 281, 20))
        self.lineEditusername.setText("")
        self.lineEditusername.setObjectName("lineEditusername")
        self.lineEditpassword = QtWidgets.QLineEdit(self.frame)
        self.lineEditpassword.setGeometry(QtCore.QRect(100, 310, 281, 20))
        self.lineEditpassword.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #1D2B64, stop:1 #F8CDDA);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0#9796f0, stop:1 #fbc7d4);")
        self.lineEditpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditpassword.setObjectName("lineEditpassword")
        self.labelusername = QtWidgets.QLabel(self.frame)
        self.labelusername.setGeometry(QtCore.QRect(20, 270, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.labelusername.setFont(font)
        self.labelusername.setStyleSheet("background-color:none;")
        self.labelusername.setObjectName("labelusername")
        self.labelpassword = QtWidgets.QLabel(self.frame)
        self.labelpassword.setGeometry(QtCore.QRect(20, 310, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelpassword.setFont(font)
        self.labelpassword.setStyleSheet("background-color: none;")
        self.labelpassword.setObjectName("labelpassword")
        self.pushButtonlogin = QtWidgets.QPushButton(self.frame)
        self.pushButtonlogin.setGeometry(QtCore.QRect(170, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonlogin.setFont(font)
        self.pushButtonlogin.setObjectName("pushButtonlogin")
        self.pushButtonMin = QtWidgets.QPushButton(Form)
        self.pushButtonMin.setGeometry(QtCore.QRect(450, 10, 18, 18))
        self.pushButtonMin.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonMin.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonMin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonMin.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"border-radius:8px;")
        self.pushButtonMin.setText("")
        self.pushButtonMin.setObjectName("pushButtonMin")
        self.pushButtonExit = QtWidgets.QPushButton(Form)
        self.pushButtonExit.setGeometry(QtCore.QRect(470, 10, 18, 18))
        self.pushButtonExit.setMinimumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"background-color: rgb(255, 255, 0);\n"
"border-radius:8px;")
        self.pushButtonExit.setText("")
        self.pushButtonExit.setObjectName("pushButtonExit")

        self.retranslateUi(Form)
        self.pushButtonMin.clicked.connect(Form.showMinimized)
        self.pushButtonExit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelusername.setText(_translate("Form", "username:"))
        self.labelpassword.setText(_translate("Form", "password:"))
        self.pushButtonlogin.setText(_translate("Form", "Login"))


