# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Panel(object):
    def setupUi(self, panel):
        panel.setObjectName("panel")
        panel.resize(500, 302)
        font = QtGui.QFont()
        font.setPointSize(12)
        panel.setFont(font)
        panel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #e65c00, stop:1 #F9D423);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #fceabb, stop:1 #f8b500);")
        self.label = QtWidgets.QLabel(panel)
        self.label.setGeometry(QtCore.QRect(210, 60, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(panel)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 161, 181))
        self.label_2.setStyleSheet("\n"
"background-color: none;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("10531505995604985291.jpg"))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(panel)
        QtCore.QMetaObject.connectSlotsByName(panel)

    def retranslateUi(self, panel):
        _translate = QtCore.QCoreApplication.translate
        panel.setWindowTitle(_translate("panel", "panel"))
        self.label.setText(_translate("panel", "Welcome to the user panel"))

